image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - hexo init .
  - npm install
  - git config --global user.name "Uyiim"
  - git config --global user.email "fiotose@gmail.com"
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
