image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/
    - themes/simpleblock/node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - cd themes/simpleblock
  - npm install
  - cd ../..
  - hexo g
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
