title: 我无所谓，但是不许你逃
date: 2015-08-07 21:56:55
tags:
  - animes
---
感觉我心里有点高兴，不知道该怎样开始讲这件事。这样的，不过是发现一部动漫，在已经末世的现在，心情舒畅。

是个老番[《吸血姬美夕》](http://baike.baidu.com/subview/112177/11252341.htm)，感觉色调蛮符合的，就看了下来。里面有着人世的美好，但更多的则是丑恶。主角只是一个观察者，几乎不受其他影响的，目的是把神魔送入黑暗，不关邪恶或是无辜，而让自己不去留意各样的人类。这样下来就是留下极大的无奈，每一集来都落不下一个好结局。对所有的态度仅仅是都可以，遥望这些荒诞的世故

接过别人的一句话，现在许多的东西，刻意的宣扬着美好的东西。太多的博爱同情，太多的热血正义，帮助什么拯救什么，让人感觉到很累，更加令我厌恶。我更想明白自己的无力，奇迹真的都不会真实。这动画里，再美好的东西，碍着就应该毫不留情的打碎。同样的，有些悲情的命运一旦发生也不能再去挽救，世界本来就是残缺的，残酷现实才是本质。

也许主角给予的永恒的幸福才是最大的悲哀吧，就仅仅沉醉那不实的梦。不用想，就是吸血姬也不会进食我，会被讨厌，因为让活着是她认为的惩罚。

然而我说得不准确，主角后来让我稍稍失望

![吸血姬美夕](http://ww2.sinaimg.cn/small/97d85706gw1euuf3538g1j20dw0m8myr.jpg)

2015.08.10 19:27重新编辑
