## Services
google_analytics: UA-63884172-1

## Meta
rss: /blog/atom.xml
favicon: /blog/favicon.png
icon: /blog/favicon.png
source_url:
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  'Home': /blog/
  'Wiki': 'https://github.com/Yailm/wiki'

right_menus:
  'Github': 'https://github.com/Yailm'
  'RSS': /blog/atom.xml

## Banners && Widgets
banners:
  markdown: |
      努力成长，终点远着

widgets:
  -
    markdown: |
        暂无内容

  -
    tags: true

  -
    archives: true

